# PostgreSQL. Versions 9.3 and up are supported.
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:development, :postgres_username) %>
  password:  <%= Rails.application.credentials.dig(:development, :postgres_password) %>

development:
  <<: *default
  database: fullstack_agriculture_game_development

test:
  <<: *default
  database: fullstack_agriculture_game_test

production:
  <<: *default
  database: fullstack_agriculture_game_production
  username: fullstack_agriculture_game
  password: <%= ENV['FULLSTACK_AGRICULTURE_GAME_DATABASE_PASSWORD'] %>
